# name: 'AntV OSCP 计划 / AntV OSCP Plan'
# description: AntV 开源共建计划(仅供管理员使用) / AntV Open Source Contribution Plan(For administrators only)
# body:
#   - type: checkboxes
#     id: AntV_OSCP_program
#     attributes:
#       label: AntV Open Source Contribution Plan（可选/Optional）
#       description: |
#         AntV 开源共建计划期望可以基于 AntV 的开源 Roadmap 开放具体开发任务到社区，以社区共建任务的形式推动“AntV” 的开源发展，也期望有更多社区伙伴各各种形式参与到 AntV 的开源共建中，共同参与数据可视化开源生态的持续建设。
#         AntV Open Source Contribution Plan expects to open specific development tasks to the community based on AntV's open source roadmap, promote the open source development of "AntV" in the form of community co-construction tasks, and also hope that more community partners will participate in AntV's open source co-construction in various forms, and jointly participate in the continuous construction of the data visualization open source ecosystem.

#         若有感兴趣想要认领的任务，可直接回复认领，如果你是首次认领可先完成初级入门任务。
#         If you are interested in claiming a task, you can directly reply to claim it. If you are claiming for the first time, you can complete the primary entry task first.

#       options:
#         - label: 我同意将这个 Issue 参与 OSCP 计划 / I agree to participate in the OSCP plan
#     validations:
#       required: false
#   - type: dropdown
#     id: issue_oscp_difficulty
#     attributes:
#       label: Issue 类型 / Issue Type
#       options:
#         - 初级任务 / Primary Task
#         - 中级任务 / Intermediate Task
#         - 高级任务 / Advanced Task
#         - 专家任务 / Expert Task
#     validations:
#       required: false
#   - type: textarea
#     id: oscp_task_description
#     attributes:
#       label: 任务介绍 / Task Description
#       description: |
#         简单描述任务背景信息，为了解决哪些问题
#         Briefly describe the background information of the task and what problems to solve
#     validations:
#       required: false
#   - type: textarea
#     id: oscp_task_info_ref
#     attributes:
#       label: 参考说明 / Reference Description
#       description: |
#         提供一些可参考的 demo，相关教程辅助用户解决问题
#         Provide some demos and related tutorials for users to solve problems
#     validations:
#       required: false