name: 'AntV OSCP 计划'
description:  AntV 开源共建计划（AntV Open Source Contribution Plan，简称 AntV OSCP）
body:
  - type: checkboxes
    id: AntV_OSCP_program
    attributes:
      label: AntV Open Source Contribution Plan（可选）
      description: |
        AntV 开源共建计划（AntV Open Source Contribution Plan，简称 AntV OSCP） 期望可以基于 AntV 的开源 Roadmap 开放具体开发任务到社区，以社区共建任务的形式推动“AntV” 的开源发展，也期望有更多社区伙伴各各种形式参与到 AntV 的开源共建中，共同参与数据可视化开源生态的持续建设。
        若有感兴趣想要认领的任务，可直接回复认领，如果你是首次认领可先完成初级入门任务。
         
      options:
        - label: 我同意将这个 Issue 参与 OSCP 计划
    validations:
      required: false
  - type: dropdown
    id: issue_oscp_difficulty
    attributes:
      label: Issue 类型
      options:
        - 初级任务
        - 中级任务
        - 高级任务
        - 专家任务
    validations:
      required: false
  - type: textarea
    id: oscp_task_description
    attributes:
      label: 任务介绍
      description: | 
        简单描述任务背景信息，为了解决哪些问题
    validations:
      required: false
  - type: textarea
    id: oscp_task_info_ref
    attributes:
      label: 参考说明
      description: | 
       提供一些可参考的 demo，相关教程辅助用户解决问题
    validations:
      required: false
  
