// Build-time schema definition; excluded from the published runtime sources.
import { ref, tuple } from './helpers';

export const interactionOptions = {
  elementHighlight: {
    link: { type: 'boolean' },
    background: { type: 'boolean' },
    offset: { type: 'number' },
    region: { type: 'boolean' },
  },
  elementHighlightByX: {
    link: { type: 'boolean' },
    background: { type: 'boolean' },
    offset: { type: 'number' },
    delay: { type: 'number' },
  },
  elementHighlightByColor: {
    color: { type: 'string' },
    background: { type: 'boolean' },
    link: { type: 'boolean' },
    offset: { type: 'number' },
    delay: { type: 'number' },
  },
  elementHoverScale: {
    scale: { type: 'number' },
    shadow: { type: 'boolean' },
    shadowColor: { type: 'string' },
    shadowBlur: { type: 'number' },
    shadowOffsetX: { type: 'number' },
    shadowOffsetY: { type: 'number' },
    zIndex: { type: 'number' },
    delay: { type: 'number' },
  },
  elementSelect: {
    single: { type: 'boolean' },
    background: { type: 'boolean' },
    offset: { type: 'number' },
    multipleSelectHotkey: { type: 'string' },
    region: { type: 'boolean' },
  },
  elementSelectByX: {
    region: { type: 'boolean' },
    single: { type: 'boolean' },
    background: { type: 'boolean' },
    offset: { type: 'number' },
  },
  elementSelectByColor: {
    single: { type: 'boolean' },
    background: { type: 'boolean' },
    offset: { type: 'number' },
  },
  fisheye: {
    wait: { type: 'number' },
    leading: { type: 'boolean' },
    trailing: { type: 'boolean' },
    focusX: { type: 'number' },
    focusY: { type: 'number' },
    distortionX: { type: 'number' },
    distortionY: { type: 'number' },
    visual: { type: 'boolean' },
  },
  chartIndex: {
    wait: { type: 'number' },
    leading: { type: 'boolean' },
    trailing: { type: 'boolean' },
  },
  tooltip: {
    shared: { type: 'boolean' },
    series: { type: 'boolean' },
    facet: { type: 'boolean' },
    body: { type: 'boolean' },
    crosshairs: { type: 'boolean' },
    marker: { type: 'boolean' },
    groupName: { type: 'boolean' },
    disableNative: { type: 'boolean' },
    disableAutoHide: { type: 'boolean' },
    offset: tuple({ type: 'number' }, { type: 'number' }),
    position: { type: 'string' },
    bounding: ref('jsonObject'),
    mount: { type: 'string' },
    css: ref('jsonObject'),
    enterable: { type: 'boolean' },
  },
  brushHighlight: {
    brushKey: { type: 'string' },
    reverse: { type: 'boolean' },
    series: { type: 'boolean' },
    facet: { type: 'boolean' },
  },
  brushXHighlight: {
    brushKey: { type: 'string' },
    reverse: { type: 'boolean' },
    series: { type: 'boolean' },
    facet: { type: 'boolean' },
  },
  brushYHighlight: {
    brushKey: { type: 'string' },
    reverse: { type: 'boolean' },
    series: { type: 'boolean' },
    facet: { type: 'boolean' },
  },
  brushAxisHighlight: {
    brushKey: { type: 'string' },
    reverse: { type: 'boolean' },
  },
  brushFilter: { reverse: { type: 'boolean' } },
  brushXFilter: { reverse: { type: 'boolean' } },
  brushYFilter: { reverse: { type: 'boolean' } },
  sliderFilter: {
    initDomain: ref('jsonObject'),
    className: { type: 'string' },
    prefix: { type: 'string' },
    hasState: { type: 'boolean' },
    wait: { type: 'number' },
    leading: { type: 'boolean' },
    trailing: { type: 'boolean' },
    adaptiveMode: {
      anyOf: [{ type: 'null' }, { const: false }, { const: 'filter' }],
    },
  },
  poptip: { offsetX: { type: 'number' }, offsetY: { type: 'number' } },
  drillDown: { breadCrumb: ref('jsonObject') },
};
