import { ValueAttribute, ObjectAttribute, ArrayAttribute } from '../types';
import { Geometry } from '../../spec';

export type API<Props extends Geometry, Mark> = {
  data: ValueAttribute<Props['data'], Mark>;
  encode: ObjectAttribute<Props['encode'], Mark>;
  scale: ObjectAttribute<Props['scale'], Mark>;
  transform: ArrayAttribute<Props['transform'], Mark>;
  animate: ObjectAttribute<Props['animate'], Mark>;
  key: ValueAttribute<Props['key'], Mark>;
  label: ArrayAttribute<Props['labels'], Mark>;
  class: ValueAttribute<Props['class'], Mark>;
  style: ObjectAttribute<Props['style'], Mark>;
  facet: ValueAttribute<Props['facet'], Mark>;
  axis: ObjectAttribute<Props['axis'], Mark>;
  legend: ObjectAttribute<Props['legend'], Mark>;
  coordinate: ArrayAttribute<Props['coordinates'], Mark>;
  interaction: ArrayAttribute<Props['interactions'], Mark>;
  paddingLeft: ValueAttribute<Props['paddingLeft'], Mark>;
  paddingRight: ValueAttribute<Props['paddingRight'], Mark>;
  paddingBottom: ValueAttribute<Props['paddingBottom'], Mark>;
  paddingTop: ValueAttribute<Props['paddingTop'], Mark>;
  padding: ValueAttribute<Props['padding'], Mark>;
  insetLeft: ValueAttribute<Props['insetLeft'], Mark>;
  insetTop: ValueAttribute<Props['insetTop'], Mark>;
  insetBottom: ValueAttribute<Props['insetBottom'], Mark>;
  insetRight: ValueAttribute<Props['insetRight'], Mark>;
  inset: ValueAttribute<Props['inset'], Mark>;
  marginLeft: ValueAttribute<Props['marginLeft'], Mark>;
  marginTop: ValueAttribute<Props['marginTop'], Mark>;
  marginBottom: ValueAttribute<Props['marginBottom'], Mark>;
  marginRight: ValueAttribute<Props['marginBottom'], Mark>;
  margin: ValueAttribute<Props['margin'], Mark>;
  frame: ValueAttribute<Props['frame'], Mark>;
  layout?: ObjectAttribute<Props['layout'], Mark>;
};
