export { Category10 } from './category10';
export { Category20 } from './category20';
export { Tableau10 } from './tableau10';
export { SequentialBlue } from './sequentialBlue';
export { SequentialDarkBlue } from './sequentialDarkBlue';
export { SequentialGreen } from './sequentialGreen';
export { SequentialDarkGreen } from './sequentialDarkGreen';
export { SequentialGrey } from './sequentialGrey';
export { SequentialOrange } from './sequentialOrange';
export { SequentialPink } from './sequentialPink';
export { SequentialRed } from './sequentialRed';
export { SequentialYellow } from './sequentialYellow';
export { SequentialPurple } from './sequentialPurple';
export { SequentialYellowOrange } from './sequentialYellowOrange';
export { SequentialYellowGreen } from './sequentialYellowGreen';
export { SequentialPinkPurple } from './sequentialPinkPurple';
export { SequentialGreenBlue } from './sequentialGreenBlue';
export { DivergingGreenYellow } from './divergingGreenYellow';
export { DivergingRedBlue } from './divergingRedBlue';
export { DivergingGreenRed } from './divergingGreenRed';
export { DivergingRedPurple } from './divergingRedPurple';

export type { Category10Options } from './category10';
export type { Category20Options } from './category20';
export type { SequentialBlueOptions } from './sequentialBlue';
export type { SequentialDarkBlueOptions } from './sequentialDarkBlue';
export type { SequentialGreenOptions } from './sequentialGreen';
export type { SequentialDarkGreenOptions } from './sequentialDarkGreen';
export type { SequentialGreyOptions } from './sequentialGrey';
export type { SequentialOrangeOptions } from './sequentialOrange';
export type { SequentialPinkOptions } from './sequentialPink';
export type { SequentialRedOptions } from './sequentialRed';
export type { SequentialYellowOptions } from './sequentialYellow';
export type { SequentialPurpleOptions } from './sequentialPurple';
export type { SequentialYellowOrangeOptions } from './sequentialYellowOrange';
export type { SequentialYellowGreenOptions } from './sequentialYellowGreen';
export type { SequentialPinkPurpleOptions } from './sequentialPinkPurple';
export type { SequentialGreenBlueOptions } from './sequentialGreenBlue';
export type { DivergingGreenYellowOptions } from './divergingGreenYellow';
export type { DivergingRedBlueOptions } from './divergingRedBlue';
export type { DivergingGreenRedOptions } from './divergingGreenRed';
export type { DivergingRedPurpleOptions } from './divergingRedPurple';
