import { TreeNode } from '../Tree';

export const scaleConfig: TreeNode[] = [
  // 比例尺配置
  {
    id: 'mark.scale',
    label: 'scale',
    type: 'Record<ChannelTypes, Scale>',
    description: '比例尺|比例尺映射',
    optional: true,
    children: [
      // 线性比例尺
      {
        id: 'mark.scale.linear',
        label: 'LinearScale',
        type: 'Object',
        description: '线性比例尺',
        children: [
          {
            id: 'mark.scale.linear.type',
            label: 'type',
            type: "'linear'",
            description: '比例尺类型',
            optional: true,
          },
          // BaseScale 通用属性
          {
            id: 'mark.scale.linear.palette',
            label: 'palette',
            type: "Palette['type'] | string",
            description: '调色板',
            optional: true,
          },
          {
            id: 'mark.scale.linear.rangeMax',
            label: 'rangeMax',
            type: 'number',
            description: '值域最大值',
            optional: true,
          },
          {
            id: 'mark.scale.linear.rangeMin',
            label: 'rangeMin',
            type: 'number',
            description: '值域最小值',
            optional: true,
          },
          {
            id: 'mark.scale.linear.domainMax',
            label: 'domainMax',
            type: 'number',
            description: '定义域最大值',
            optional: true,
          },
          {
            id: 'mark.scale.linear.domainMin',
            label: 'domainMin',
            type: 'number',
            description: '定义域最小值',
            optional: true,
          },
          {
            id: 'mark.scale.linear.key',
            label: 'key',
            type: 'string',
            description: '比例尺键名',
            optional: true,
          },
          {
            id: 'mark.scale.linear.facet',
            label: 'facet',
            type: 'boolean',
            description: '是否分面',
            optional: true,
          },
          {
            id: 'mark.scale.linear.independent',
            label: 'independent',
            type: 'boolean',
            description: '是否独立',
            optional: true,
          },
          {
            id: 'mark.scale.linear.zero',
            label: 'zero',
            type: 'boolean',
            description: '是否包含零点',
            optional: true,
          },
          {
            id: 'mark.scale.linear.offset',
            label: 'offset',
            type: '(t: number) => number',
            description: '偏移函数',
            optional: true,
          },
          {
            id: 'mark.scale.linear.relations',
            label: 'relations',
            type: '[any, any][]',
            description: '关系映射',
            optional: true,
          },
          {
            id: 'mark.scale.linear.groupTransform',
            label: 'groupTransform',
            type: '(scales: QuantitativeScale[]) => void',
            description: '分组变换',
            optional: true,
          },
          // LinearOptions 特有属性
          {
            id: 'mark.scale.linear.domain',
            label: 'domain',
            type: '[number, number]',
            description: '定义域',
            optional: true,
          },
          {
            id: 'mark.scale.linear.range',
            label: 'range',
            type: '[number, number]',
            description: '值域',
            optional: true,
          },
          {
            id: 'mark.scale.linear.nice',
            label: 'nice',
            type: 'boolean',
            description: '优化刻度',
            optional: true,
          },
          {
            id: 'mark.scale.linear.clamp',
            label: 'clamp',
            type: 'boolean',
            description: '限制范围',
            optional: true,
          },
        ],
      },
      // 序数比例尺
      {
        id: 'mark.scale.ordinal',
        label: 'OrdinalScale',
        type: 'Object',
        description: '序数比例尺',
        children: [
          {
            id: 'mark.scale.ordinal.type',
            label: 'type',
            type: "'ordinal'",
            description: '比例尺类型',
            optional: true,
          },
          {
            id: 'mark.scale.ordinal.domain',
            label: 'domain',
            type: 'any[]',
            description: '定义域',
            optional: true,
          },
          {
            id: 'mark.scale.ordinal.range',
            label: 'range',
            type: 'any[]',
            description: '值域',
            optional: true,
          },
          {
            id: 'mark.scale.ordinal.unknown',
            label: 'unknown',
            type: 'any',
            description: '未知值映射',
            optional: true,
          },
        ],
      },
      // 分类比例尺
      {
        id: 'mark.scale.band',
        label: 'BandScale',
        type: 'Object',
        description: '分类比例尺',
        children: [
          {
            id: 'mark.scale.band.type',
            label: 'type',
            type: "'band'",
            description: '比例尺类型',
            optional: true,
          },
          {
            id: 'mark.scale.band.domain',
            label: 'domain',
            type: 'string[]',
            description: '分类域',
            optional: true,
          },
          {
            id: 'mark.scale.band.range',
            label: 'range',
            type: '[number, number]',
            description: '值域',
            optional: true,
          },
          {
            id: 'mark.scale.band.padding',
            label: 'padding',
            type: 'number',
            description: '间距',
            optional: true,
          },
          {
            id: 'mark.scale.band.paddingInner',
            label: 'paddingInner',
            type: 'number',
            description: '内部间距',
            optional: true,
          },
          {
            id: 'mark.scale.band.paddingOuter',
            label: 'paddingOuter',
            type: 'number',
            description: '外部间距',
            optional: true,
          },
          {
            id: 'mark.scale.band.align',
            label: 'align',
            type: 'number',
            description: '对齐方式',
            optional: true,
          },
        ],
      },
      // 点比例尺
      {
        id: 'mark.scale.point',
        label: 'PointScale',
        type: 'Object',
        description: '点比例尺',
        children: [
          {
            id: 'mark.scale.point.type',
            label: 'type',
            type: "'point'",
            description: '比例尺类型',
            optional: true,
          },
          {
            id: 'mark.scale.point.domain',
            label: 'domain',
            type: 'string[]',
            description: '定义域',
            optional: true,
          },
          {
            id: 'mark.scale.point.range',
            label: 'range',
            type: '[number, number]',
            description: '值域',
            optional: true,
          },
          {
            id: 'mark.scale.point.padding',
            label: 'padding',
            type: 'number',
            description: '间距',
            optional: true,
          },
          {
            id: 'mark.scale.point.align',
            label: 'align',
            type: 'number',
            description: '对齐方式',
            optional: true,
          },
        ],
      },
      // 时间比例尺
      {
        id: 'mark.scale.time',
        label: 'TimeScale',
        type: 'Object',
        description: '时间比例尺',
        children: [
          {
            id: 'mark.scale.time.type',
            label: 'type',
            type: "'time'",
            description: '比例尺类型',
            optional: true,
          },
          {
            id: 'mark.scale.time.domain',
            label: 'domain',
            type: '[Date, Date]',
            description: '时间域',
            optional: true,
          },
          {
            id: 'mark.scale.time.range',
            label: 'range',
            type: '[number, number]',
            description: '值域',
            optional: true,
          },
          {
            id: 'mark.scale.time.nice',
            label: 'nice',
            type: 'boolean',
            description: '优化刻度',
            optional: true,
          },
          {
            id: 'mark.scale.time.clamp',
            label: 'clamp',
            type: 'boolean',
            description: '限制范围',
            optional: true,
          },
        ],
      },
      // 对数比例尺
      {
        id: 'mark.scale.log',
        label: 'LogScale',
        type: 'Object',
        description: '对数比例尺',
        children: [
          {
            id: 'mark.scale.log.type',
            label: 'type',
            type: "'log'",
            description: '比例尺类型',
            optional: true,
          },
          {
            id: 'mark.scale.log.domain',
            label: 'domain',
            type: '[number, number]',
            description: '定义域',
            optional: true,
          },
          {
            id: 'mark.scale.log.range',
            label: 'range',
            type: '[number, number]',
            description: '值域',
            optional: true,
          },
          {
            id: 'mark.scale.log.base',
            label: 'base',
            type: 'number',
            description: '对数底数',
            optional: true,
          },
          {
            id: 'mark.scale.log.nice',
            label: 'nice',
            type: 'boolean',
            description: '优化刻度',
            optional: true,
          },
          {
            id: 'mark.scale.log.clamp',
            label: 'clamp',
            type: 'boolean',
            description: '限制范围',
            optional: true,
          },
        ],
      },
      // 幂比例尺
      {
        id: 'mark.scale.pow',
        label: 'PowScale',
        type: 'Object',
        description: '幂比例尺',
        children: [
          {
            id: 'mark.scale.pow.type',
            label: 'type',
            type: "'pow'",
            description: '比例尺类型',
            optional: true,
          },
          {
            id: 'mark.scale.pow.domain',
            label: 'domain',
            type: '[number, number]',
            description: '定义域',
            optional: true,
          },
          {
            id: 'mark.scale.pow.range',
            label: 'range',
            type: '[number, number]',
            description: '值域',
            optional: true,
          },
          {
            id: 'mark.scale.pow.exponent',
            label: 'exponent',
            type: 'number',
            description: '指数',
            optional: true,
          },
          {
            id: 'mark.scale.pow.nice',
            label: 'nice',
            type: 'boolean',
            description: '优化刻度',
            optional: true,
          },
          {
            id: 'mark.scale.pow.clamp',
            label: 'clamp',
            type: 'boolean',
            description: '限制范围',
            optional: true,
          },
        ],
      },
      // 平方根比例尺
      {
        id: 'mark.scale.sqrt',
        label: 'SqrtScale',
        type: 'Object',
        description: '平方根比例尺',
        children: [
          {
            id: 'mark.scale.sqrt.type',
            label: 'type',
            type: "'sqrt'",
            description: '比例尺类型',
            optional: true,
          },
          {
            id: 'mark.scale.sqrt.domain',
            label: 'domain',
            type: '[number, number]',
            description: '定义域',
            optional: true,
          },
          {
            id: 'mark.scale.sqrt.range',
            label: 'range',
            type: '[number, number]',
            description: '值域',
            optional: true,
          },
          {
            id: 'mark.scale.sqrt.nice',
            label: 'nice',
            type: 'boolean',
            description: '优化刻度',
            optional: true,
          },
          {
            id: 'mark.scale.sqrt.clamp',
            label: 'clamp',
            type: 'boolean',
            description: '限制范围',
            optional: true,
          },
        ],
      },
      // 阈值比例尺
      {
        id: 'mark.scale.threshold',
        label: 'ThresholdScale',
        type: 'Object',
        description: '阈值比例尺',
        children: [
          {
            id: 'mark.scale.threshold.type',
            label: 'type',
            type: "'threshold'",
            description: '比例尺类型',
            optional: true,
          },
          {
            id: 'mark.scale.threshold.domain',
            label: 'domain',
            type: 'number[]',
            description: '阈值数组',
            optional: true,
          },
          {
            id: 'mark.scale.threshold.range',
            label: 'range',
            type: 'any[]',
            description: '值域',
            optional: true,
          },
        ],
      },
      // 分位数比例尺
      {
        id: 'mark.scale.quantile',
        label: 'QuantileScale',
        type: 'Object',
        description: '分位数比例尺',
        children: [
          {
            id: 'mark.scale.quantile.type',
            label: 'type',
            type: "'quantile'",
            description: '比例尺类型',
            optional: true,
          },
          {
            id: 'mark.scale.quantile.domain',
            label: 'domain',
            type: 'number[]',
            description: '数据域',
            optional: true,
          },
          {
            id: 'mark.scale.quantile.range',
            label: 'range',
            type: 'any[]',
            description: '值域',
            optional: true,
          },
        ],
      },
      // 分段比例尺
      {
        id: 'mark.scale.quantize',
        label: 'QuantizeScale',
        type: 'Object',
        description: '分段比例尺',
        children: [
          {
            id: 'mark.scale.quantize.type',
            label: 'type',
            type: "'quantize'",
            description: '比例尺类型',
            optional: true,
          },
          {
            id: 'mark.scale.quantize.domain',
            label: 'domain',
            type: '[number, number]',
            description: '定义域',
            optional: true,
          },
          {
            id: 'mark.scale.quantize.range',
            label: 'range',
            type: 'any[]',
            description: '值域',
            optional: true,
          },
        ],
      },
      // 序列比例尺
      {
        id: 'mark.scale.sequential',
        label: 'SequentialScale',
        type: 'Object',
        description: '序列比例尺',
        children: [
          {
            id: 'mark.scale.sequential.type',
            label: 'type',
            type: "'sequential'",
            description: '比例尺类型',
            optional: true,
          },
          {
            id: 'mark.scale.sequential.domain',
            label: 'domain',
            type: '[number, number]',
            description: '定义域',
            optional: true,
          },
          {
            id: 'mark.scale.sequential.interpolator',
            label: 'interpolator',
            type: '(t: number) => any',
            description: '插值函数',
            optional: true,
          },
          {
            id: 'mark.scale.sequential.clamp',
            label: 'clamp',
            type: 'boolean',
            description: '限制范围',
            optional: true,
          },
        ],
      },
      // 恒定比例尺
      {
        id: 'mark.scale.constant',
        label: 'ConstantScale',
        type: 'Object',
        description: '恒定比例尺',
        children: [
          {
            id: 'mark.scale.constant.type',
            label: 'type',
            type: "'constant'",
            description: '比例尺类型',
            optional: true,
          },
          {
            id: 'mark.scale.constant.value',
            label: 'value',
            type: 'any',
            description: '恒定值',
            optional: true,
          },
        ],
      },
      // 恒等比例尺
      {
        id: 'mark.scale.identity',
        label: 'IdentityScale',
        type: 'Object',
        description: '恒等比例尺',
        children: [
          {
            id: 'mark.scale.identity.type',
            label: 'type',
            type: "'identity'",
            description: '比例尺类型',
            optional: true,
          },
          {
            id: 'mark.scale.identity.domain',
            label: 'domain',
            type: 'any[]',
            description: '定义域',
            optional: true,
          },
        ],
      },
    ],
  },
];
