name: build

on: [push]

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '14'

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run CI
        run: |
          npm install
          npm run ci

      - name: Upload snapshots to GitHub Actions Artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: snapshots
          path: __tests__/integration/snapshots/static/
          retention-days: 1

      - name: Update coverall
        if: ${{ success() }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
