name: Surge PR Preview - Build Stage

on: pull_request_target

jobs:
  build-preview:
    runs-on: ubuntu-latest
    steps:
      - name: checkout PR
        uses: actions/checkout@v2
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merge
      - name: build dist
        run: |
          npm install
          npm run site:build
      - name: upload dist artifact
        uses: actions/upload-artifact@v2
        with:
          name: pr-build-dist
          path: public
